#!/bin/bash
# global settings.  If these values are set prior to sourcing this file,
#                   the earlier value will be retained.
#                   Adjust these values for your system.

# setup the IP address of the DUT, use a domain name if using a CA certificate
# Domain name is assumed to be provided by DNS or /etc/hosts
if [ -z "$IPADDR" ]
then
    IPADDR=192.168.1.233
else
    sed -i 's/^    IPADDR=.*$/    IPADDR='"${IPADDR}"'/g' global_settings
fi
if [[ -z "$IPADDR" && -z "$URL" ]]
then
    echo "IPADDR variable needs to be set."
    exit 1
fi

function smart_jq {
    local input=$(cat)
    if [ "${input:0:1}" == "{" ]; then
        echo "${input}" | jq
    else
        echo "${input}"
    fi
}

# Use jq if it is installed.
if [ -z "${JQ_APP+x}" ]
then
    if ! command -v jq &> /dev/null
    then
        # recommend installing the jq application
        JQ_APP=tee
    else
        JQ_APP=smart_jq
    fi
fi

# Path to the CA certificate to use for server authentication, leave blank for default insecure mode
AUTH_CA_CERT=""
# Path to the client certificate and key to use for mutual authentication, leave blank for default insecure mode
AUTH_CLIENT_CERT=""
AUTH_CLIENT_KEY=""

# Set authentication type to use for the WebLCM API, one of:
#  - "insecure" for no authentication using username/password (default)
#  - "server-only" for server authentication using a CA certificate and username/password
#  - "mutual" for server and client authentication using CA certificate and client key/certificate pair
AUTH_TYPE="${AUTH_TYPE:-insecure}"
case "${AUTH_TYPE}" in
    insecure)
        AUTH_OPT="--insecure -b cookie -c cookie"
        ;;
    server-only)
        AUTH_OPT="--cacert ${AUTH_CA_CERT} -b cookie -c cookie"
        ;;
    mutual)
        AUTH_OPT="--cacert ${AUTH_CA_CERT} --cert ${AUTH_CLIENT_CERT} --key ${AUTH_CLIENT_KEY}"
        ;;
    *)
        echo "Invalid AUTH_TYPE: ${AUTH_TYPE}"
        exit 1
        ;;
esac

URL="${URL:-"https://${IPADDR}"}"
WEBLCM_USERNAME="${WEBLCM_USERNAME:-root}"
WEBLCM_PASSWORD="${WEBLCM_PASSWORD:-Config123!}"
ORIGINAL_WEBLCM_PASSWORD="${ORIGINAL_WEBLCM_PASSWORD:-summit}"

WL_USERNAME="${WL_USERNAME:-user1}"
WL_PASSWORD="${WL_PASSWORD:-user1}"
CONNECTION_NAME="${CONNECTION_NAME:-"UNSET"}"
SSID="${SSID:-${CONNECTION_NAME}}"
PRIVATE_KEY="${PRIVATE_KEY:-user1.pfx}"
PRIVATE_KEY_PASSWORD="${PRIVATE_KEY_PASSWORD:-user1}"
ANONYMOUS_IDENTITY="${ANONYMOUS_IDENTITY:-anonNAME}"
CA_CERT="${CA_CERT:-SystestCA.cer}"
BT_CONTROLLER="${BT_CONTROLLER:-controller0}"

CURL_APP="${CURL_APP:-curl}"
